source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.3"

gemspec

gem 'awesome_print'

gem 'pry'

gem 'jwt'

gem 'activesupport'

gem 'santa_cruz', git: 'https://github.com/ArthurFerraz07/ruby-monorepo-multiapps.git', branch: 'main'
