source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.3"

gemspec

gem 'awesome_print'

gem 'pry'

gem 'jwt'

gem 'activesupport'

gem 'httparty'

gem 'santa_cruz', path: '../santa_cruz'
