source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in identity_engine.gemspec.
gemspec

gem "pg"

gem "sprockets-rails"

# # Use the Puma web server [https://github.com/puma/puma]
# gem "puma", "~> 5.0"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
